### Exercise 2 
#### Jeremias Shadbolt 1900386

In [29]:
# Import necessary libraries 
import numpy as np
import pandas as pd
from scipy import stats
import statsmodels

1. Apply a multivariable test and obtain P-value for

a) 2,3,5,4,4,3 4,2,3,5,2,3 3,1,4,4,3,5

b) Fi,Sw,Fi,No,Sw,Fi No,Sw,No,Fi,Fi,Fi Sw,Fi,No,Sw,Sw,No


In [60]:
dataset_a = np.array([2,3,5,4,4,3,4,2,3,5,2,3,3,1,4,4,3,5])
dataset_b = np.array(["Fi","Sw","Fi","No","Sw","Fi","No","Sw","No","Fi","Fi","Fi", "Sw","Fi","No","Sw","Sw","No"])

In [20]:
# To perform a multivariable test for data a) we need to split it into >2 sets, so 3 equal sized sets
dataset_a_1, dataset_a_2, dataset_a_3 = np.split(dataset_a, len(dataset_a) // 6)

In [21]:
# verify partition
print(dataset_a_1)
print(dataset_a_2)
print(dataset_a_3)

[2 3 5 4 4 3]
[4 2 3 5 2 3]
[3 1 4 4 3 5]


In [28]:
# check for normality
print(f"P-value from Shapiro Wilk test is {stats.shapiro(dataset_a_1).pvalue:.2f}")
print(f"P-value from Shapiro Wilk test is {stats.shapiro(dataset_a_2).pvalue:.2f}")
print(f"P-value from Shapiro Wilk test is {stats.shapiro(dataset_a_3).pvalue:.2f}")

P-value from Shapiro Wilk test is 0.82
P-value from Shapiro Wilk test is 0.42
P-value from Shapiro Wilk test is 0.55


In [47]:
# ANOVA test
pvalue = stats.f_oneway(dataset_a_1, dataset_a_2, dataset_a_3)
print(f"P-value for dataset a) with ANOVA is {pvalue.pvalue:.2f}")

P-value for dataset a) with ANOVA is 0.89


In [53]:
# To perform a multivariable test for data b) we need to split it into an array of multiple arrays
dataset_b_1 = np.split(dataset_b, len(dataset_b) // 6)

In [54]:
# verify partition
print(dataset_b_1)

[array(['Fi', 'Sw', 'Fi', 'No', 'Sw', 'Fi'], dtype='<U2'), array(['No', 'Sw', 'No', 'Fi', 'Fi', 'Fi'], dtype='<U2'), array(['Sw', 'Fi', 'No', 'Sw', 'Sw', 'No'], dtype='<U2')]


In [61]:
# No idea for this one lol :D

Identify type of variables and methods used to create

a) Article_4 and Figure 3 (J).

b) Article_5 and Figure 1.


a) was ANOVA
b) was Pearson's Chi

3. In this exercise we consider file simulated_data_2_5.csv. It has four groups of 100

observation: F, G, H and I. Apply multivariable test and obtain P-value

a) to compare columns F, G and H.

b) to compare columns F, G and I.


In [175]:
data = pd.read_csv('simulated_data_2_5.csv')
data

Unnamed: 0      F      G     H      I
0            1  27.42  24.02  0.00   9.96
1            2 -11.29  20.90  4.67   5.66
2            3   7.26 -20.06  6.34  15.53
3            4  12.66  36.97  8.12   6.08
4            5   8.09 -13.34  1.25  10.31
..         ...    ...    ...   ...    ...
95          96 -17.22  21.72  3.05  14.14
96          97 -22.63   8.08  3.67  10.70
97          98 -29.18  11.73  5.73  18.91
98          99   1.60  36.30  4.19  18.24
99         100  13.06   2.58  0.75   9.12

[100 rows x 5 columns]

In [176]:
pvalue = stats.f_oneway(data['F'], data['G'], data['H'])
print(f"P-value for dataset 3 a) with ANOVA is {pvalue.pvalue:.2f}")

P-value for dataset 3 a) with ANOVA is 0.04


In [182]:
pvalue = stats.kruskal(data['F'], data['G'], data['I'])
print(f"P-value for dataset 3 b) with Kruskaali is {pvalue.pvalue:.20f}")

P-value for dataset 3 b) with Kruskaali is 0.00000001199032716665


## 4
#### no idea my friend but I'm certain we'll discuss it on Thursday

5. In this exercise we use `Horse Colic data set` from

https://archive.ics.uci.edu/ml/datasets/Horse+Colic (the `horse-colic.data` file under `Data

Folder`), which contained in the UCI Machine Learning Repository. Download the data, read

it to your software and make sure that the missing values (question marks) are handled

correctly.

Does the horse colic data provide statistical evidence that the mean `rectal temperature` or

`age` or `pulse` are different between colic horses treated without surgery and those treated

with surgery?


In [171]:
data = pd.read_csv('horse-colic.data', header = None, na_values = "?", delim_whitespace = True)

In [172]:
data

0   1        2     3      4     5    6    7    8    9   ...    18    19  \
0    2.0   1   530101  38.5   66.0  28.0  3.0  3.0  NaN  2.0  ...  45.0   8.4   
1    1.0   1   534817  39.2   88.0  20.0  NaN  NaN  4.0  1.0  ...  50.0  85.0   
2    2.0   1   530334  38.3   40.0  24.0  1.0  1.0  3.0  1.0  ...  33.0   6.7   
3    1.0   9  5290409  39.1  164.0  84.0  4.0  1.0  6.0  2.0  ...  48.0   7.2   
4    2.0   1   530255  37.3  104.0  35.0  NaN  NaN  6.0  2.0  ...  74.0   7.4   
..   ...  ..      ...   ...    ...   ...  ...  ...  ...  ...  ...   ...   ...   
295  1.0   1   533886   NaN  120.0  70.0  4.0  NaN  4.0  2.0  ...  55.0  65.0   
296  2.0   1   527702  37.2   72.0  24.0  3.0  2.0  4.0  2.0  ...  44.0   NaN   
297  1.0   1   529386  37.5   72.0  30.0  4.0  3.0  4.0  1.0  ...  60.0   6.8   
298  1.0   1   530612  36.5  100.0  24.0  3.0  3.0  3.0  1.0  ...  50.0   6.0   
299  1.0   1   534618  37.2   40.0  20.0  NaN  NaN  NaN  NaN  ...  36.0  62.0   

      20   21   22  23     24  25  26  27  
0    NaN  NaN  2.0   2  11300   0   0   2  
1    2.0  2.0  3.0   2   2208   0   0   2  
2    NaN  NaN  1.0   2      0   0   0   1  
3    3.0  5.3  2.0   1   2208   0   0   1  
4    NaN  NaN  2.0   2   4300   0   0   2  
..   ...  ...  ...  ..    ...  ..  ..  ..  
295  NaN  NaN  3.0   2   3205   0   0   2  
296  3.0  3.3  3.0   1   2208   0   0   1  
297  NaN  NaN  2.0   1   3205   0   0   2  
298  3.0  3.4  1.0   1   2208   0   0   1  
299  1.0  1.0  3.0   2   6112   0   0   2  

[300 rows x 28 columns]

In [173]:
data = data.fillna(0)
data

0   1        2     3      4     5    6    7    8    9   ...    18    19  \
0    2.0   1   530101  38.5   66.0  28.0  3.0  3.0  0.0  2.0  ...  45.0   8.4   
1    1.0   1   534817  39.2   88.0  20.0  0.0  0.0  4.0  1.0  ...  50.0  85.0   
2    2.0   1   530334  38.3   40.0  24.0  1.0  1.0  3.0  1.0  ...  33.0   6.7   
3    1.0   9  5290409  39.1  164.0  84.0  4.0  1.0  6.0  2.0  ...  48.0   7.2   
4    2.0   1   530255  37.3  104.0  35.0  0.0  0.0  6.0  2.0  ...  74.0   7.4   
..   ...  ..      ...   ...    ...   ...  ...  ...  ...  ...  ...   ...   ...   
295  1.0   1   533886   0.0  120.0  70.0  4.0  0.0  4.0  2.0  ...  55.0  65.0   
296  2.0   1   527702  37.2   72.0  24.0  3.0  2.0  4.0  2.0  ...  44.0   0.0   
297  1.0   1   529386  37.5   72.0  30.0  4.0  3.0  4.0  1.0  ...  60.0   6.8   
298  1.0   1   530612  36.5  100.0  24.0  3.0  3.0  3.0  1.0  ...  50.0   6.0   
299  1.0   1   534618  37.2   40.0  20.0  0.0  0.0  0.0  0.0  ...  36.0  62.0   

      20   21   22  23     24  25  26  27  
0    0.0  0.0  2.0   2  11300   0   0   2  
1    2.0  2.0  3.0   2   2208   0   0   2  
2    0.0  0.0  1.0   2      0   0   0   1  
3    3.0  5.3  2.0   1   2208   0   0   1  
4    0.0  0.0  2.0   2   4300   0   0   2  
..   ...  ...  ...  ..    ...  ..  ..  ..  
295  0.0  0.0  3.0   2   3205   0   0   2  
296  3.0  3.3  3.0   1   2208   0   0   1  
297  0.0  0.0  2.0   1   3205   0   0   2  
298  3.0  3.4  1.0   1   2208   0   0   1  
299  1.0  1.0  3.0   2   6112   0   0   2  

[300 rows x 28 columns]